export const FETCH_cities_SUCCESS= 'FETCH_cities_SUCCESS';
export const FETCH_LOCAL_CITIES_SUCCESS= 'FETCH_LOCAL_CITIES_SUCCESS';
export const SEARCH_CITY= 'SEARCH_CITY';
export const ADD_MY_CITY= 'ADD_MY_CITY';
export const REMOVE_MY_CITY= 'REMOVE_MY_CITY';
